import { test, expect } from '@playwright/test'

test('published item survives reload, appears in grids, favorites and orders with its locale', async ({ page }) => {
  await page.goto('/en/publish')
  await page.getByLabel('标题', { exact: true }).fill('Demo publication regression')
  await page.getByLabel('详细描述').fill('A locally published demo item for the regression test.')
  await page.getByRole('tab', { name: '数字资产' }).click()
  await page.getByLabel('商品分类').selectOption('software_source')
  await page.getByPlaceholder('0.00', { exact: true }).fill('25')
  await page.getByRole('combobox').last().click()
  await page.getByRole('option', { name: '下载链接（GitHub / 网盘）' }).click()
  await page.getByLabel('交付示例').fill('https://example.com/demo')
  await page.getByRole('button', { name: '立即发布' }).click()
  await expect(page).toHaveURL(/\/en\/listing\/item_user_/)
  const detailUrl = page.url()
  await expect(page.locator('h1')).toHaveText('Demo publication regression')
  await page.reload()
  await expect(page.locator('h1')).toHaveText('Demo publication regression')
  await page.getByRole('button', { name: '收藏', exact: true }).click()
  await expect(page.locator('header').getByRole('link', { name: /Favorites/ })).toContainText('1')
  await page.goto('/en/favorites')
  await expect(page.getByRole('link', { name: /Demo publication regression/ })).toBeVisible()
  await page.goto('/en/explore?category=software_source')
  await expect(page.getByRole('link', { name: /Demo publication regression/ })).toBeVisible()
  await expect(page.getByRole('link', { name: /iPhone 15 Pro/ })).toHaveCount(0)
  await page.goto('/en')
  await expect(page.getByRole('link', { name: /Demo publication regression/ }).first()).toBeVisible()
  await page.goto('/en/seller/seller_001')
  await expect(page.getByRole('link', { name: /Demo publication regression/ })).toBeVisible()
  await page.goto('/en/me')
  await expect(page.locator('section').filter({ has: page.getByRole('heading', { name: '📦 在售商品' }) }).getByRole('link', { name: /Demo publication regression/ })).toBeVisible()
  await page.reload()
  await expect(page.locator('section').filter({ has: page.getByRole('heading', { name: '📦 在售商品' }) }).getByRole('link', { name: /Demo publication regression/ })).toBeVisible()
  await page.goto(detailUrl)
  await page.getByRole('button', { name: '立即购买' }).click()
  await page.getByRole('button', { name: '确认下单' }).click()
  await page.getByRole('button', { name: '查看订单' }).click()
  await expect(page).toHaveURL(/\/en\/me$/)
  const orderTitle = page.getByRole('tabpanel').getByRole('link', { name: 'Demo publication regression' }).filter({ hasText: 'Demo publication regression' })
  await expect(orderTitle).toBeVisible()
  await expect(orderTitle).toHaveAttribute('href', new URL(detailUrl).pathname)
})

test('missing physical condition is explained at the field', async ({ page }) => {
  await page.goto('/zh-CN/publish')
  await page.getByLabel('标题', { exact: true }).fill('Test physical publication')
  await page.getByLabel('详细描述').fill('This item has no condition selected.')
  await page.getByPlaceholder('0.00', { exact: true }).fill('20')
  await page.getByRole('button', { name: '立即发布' }).click()
  await expect(page.getByText('请选择物品成色', { exact: true })).toBeVisible()
  await expect(page).toHaveURL(/\/publish$/)
})
